version: '2.1'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-services:
        condition: service_started
    links:
      - users-services

  users-db:
    container_name: users-db
    build: ./project/db
    ports:
     - 5432:5432
    environment:
      - POSTGRESS_USER=postgress
      - POSTGRESS_PASSWORD=postgress
    healthcheck:
      test: exit 0

  users-services:
    container_name: users-service
    build: .
#    ports:
#      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
    command: gunicorn -b 0.0.0.0:5000 manage:app

